#! /bin/bash

set -euo pipefail

mkdir -p target/

if [ ! -d target/metamath-test ]; then
	pushd target/
	git clone https://github.com/david-a-wheeler/metamath-test
	popd
fi

if [ ! -f target/tapview ]; then
	pushd target/
	wget -O- https://gitlab.com/esr/tapview/-/raw/master/tapview?inline=false > tapview
	chmod +x tapview
	popd
fi

cargo test
cargo build

pushd target/metamath-test
./run-testsuite '../debug/truthpile verify' | ../tapview
